application: maze-maker
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*maze.*ps
  script: servemaze.app
- url: /statics
  static_dir: statics
- url: /.*
  script: frontpage.app
